"use client";

import { useRef } from "react";
import "./tree.scss";
import useDpi from "./hooks/useDpi";

export default function Home() {
  const treeRef = useRef<HTMLDivElement | null>(null);
  useDpi(treeRef);

  return (
    <>
      <h1>Example DOM structure diagram with rounded connectors</h1>
      <div className="tree" ref={treeRef}>
        <ul>
          <li>
            <code>html</code>
            <ul>
              <li>
                <code>head</code>
                <ul>
                  <li>
                    <code>title</code>
                  </li>
                </ul>
              </li>
              <li>
                <code>body</code>
                <ul>
                  <li>
                    <code>header</code>
                    <ul>
                      <li>
                        <code>h1</code>
                      </li>
                      <li>
                        <code>p</code>
                      </li>
                    </ul>
                  </li>
                  <li>
                    <code>nav</code>
                    <ul>
                      <li>
                        <code>a</code>
                      </li>
                      <li>
                        <code>a</code>
                      </li>
                      <li>
                        <code>a</code>
                      </li>
                      <li>
                        <code>a</code>
                      </li>
                    </ul>
                  </li>
                  <li>
                    <code>main</code>
                    <ul>
                      <li>
                        <code>h1</code>
                      </li>
                      <li>
                        <code>article</code>
                        <ul>
                          <li>
                            <code>h2</code>
                          </li>
                          <li>
                            <code>p</code>
                          </li>
                          <li>
                            <code>p</code>
                          </li>
                        </ul>
                      </li>
                    </ul>
                  </li>
                  <li>
                    <code>aside</code>
                    <ul>
                      <li>
                        <code>h2</code>
                      </li>
                      <li>
                        <code>p</code>
                      </li>
                      <li>
                        <code>p</code>
                        <ul>
                          <li>
                            <code>a</code>
                          </li>
                        </ul>
                      </li>
                    </ul>
                  </li>
                  <li>
                    <code>footer</code>
                    <ul>
                      <li>
                        <code>nav</code>
                        <ul>
                          <li>
                            <code>a</code>
                          </li>
                          <li>
                            <code>a</code>
                            <ul>
                              <li>
                                <code>bpiojwaegpoijaweg</code>
                              </li>
                            </ul>
                          </li>
                          <li>
                            <code>a</code>
                            <ul>
                              <li>
                                <code>a</code>
                              </li>
                              <li>
                                <code>b</code>
                                <ul>
                                  <li>
                                    <code>a</code>
                                  </li>
                                  <li>
                                    <code>a</code>
                                  </li>
                                  <li>
                                    <code>a</code>
                                    <ul>
                                      <li>
                                        <code>a</code>
                                      </li>
                                    </ul>
                                  </li>
                                  <li>
                                    <code>a</code>
                                  </li>
                                </ul>
                              </li>
                              <li>
                                <code>c</code>
                              </li>
                            </ul>
                          </li>
                          <li>
                            <code>a</code>
                            <ul>
                              <li>
                                <code>a</code>
                              </li>
                              <li>
                                <code>b</code>
                              </li>
                              <li>
                                <code>c</code>
                              </li>
                            </ul>
                          </li>
                        </ul>
                      </li>
                    </ul>
                  </li>
                </ul>
              </li>
            </ul>
          </li>
        </ul>
      </div>
    </>
  );
}
