"use client";

import { useState } from "react";
import SmartTree from "./SmartTree";

export default function Home() {
  const [lineWidth, setLineWidth] = useState<number>(2);

  return (
    <>
      <div className="p-20 text-white grid gap-3 col-span-1">
        <h1 className="text-3xl">
          Example DOM structure diagram with rounded connectors
        </h1>
        <div className="overflow-auto">
          <table>
            <tbody>
              <tr>
                <th className="p-2">
                  <label htmlFor="line-width">Line width:</label>
                </th>
                <td className="p-2">
                  <input
                    type="range"
                    min={1}
                    max={20}
                    value={lineWidth}
                    onChange={(e) => {
                      const v = Number(e.target.value);
                      setLineWidth(v);
                    }}
                    name="line-width"
                  />
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
      <SmartTree
        lineWidth={lineWidth}
        loading={<div className="tree-loading">Loading...</div>}
      >
        <ul>
          <li>
            <code>html</code>
            <ul>
              <li>
                <code>head</code>
                <ul>
                  <li>
                    <code>title</code>
                  </li>
                </ul>
              </li>
              <li>
                <code>body</code>
                <ul>
                  <li>
                    <code>header</code>
                    <ul>
                      <li>
                        <code>h1</code>
                      </li>
                      <li>
                        <code>p</code>
                      </li>
                    </ul>
                  </li>
                  <li>
                    <code>nav</code>
                    <ul>
                      <li>
                        <code>a</code>
                      </li>
                      <li>
                        <code>a</code>
                      </li>
                      <li>
                        <code>a</code>
                      </li>
                      <li>
                        <code>a</code>
                      </li>
                    </ul>
                  </li>
                  <li>
                    <code>main</code>
                    <ul>
                      <li>
                        <code>h1</code>
                      </li>
                      <li>
                        <code>article</code>
                        <ul>
                          <li>
                            <code>h2</code>
                          </li>
                          <li>
                            <code>p</code>
                          </li>
                          <li>
                            <code>p</code>
                          </li>
                        </ul>
                      </li>
                    </ul>
                  </li>
                  <li>
                    <code>aside</code>
                    <ul>
                      <li>
                        <code>h2</code>
                      </li>
                      <li>
                        <code>p</code>
                      </li>
                      <li>
                        <code>p</code>
                        <ul>
                          <li>
                            <code>a</code>
                          </li>
                        </ul>
                      </li>
                    </ul>
                  </li>
                  <li>
                    <code>footer</code>
                    <ul>
                      <li>
                        <code>nav</code>
                        <ul>
                          <li>
                            <code>a</code>
                          </li>
                          <li>
                            <code>a</code>
                            <ul>
                              <li>
                                <code>bpiojwaegpoijaweg</code>
                              </li>
                            </ul>
                          </li>
                          <li>
                            <code>a</code>
                            <ul>
                              <li>
                                <code>a</code>
                              </li>
                              <li>
                                <code>b</code>
                                <ul>
                                  <li>
                                    <code>a</code>
                                  </li>
                                  <li>
                                    <code>a</code>
                                  </li>
                                  <li>
                                    <code>a</code>
                                    <ul>
                                      <li>
                                        <code>a</code>
                                      </li>
                                    </ul>
                                  </li>
                                  <li>
                                    <code>a</code>
                                  </li>
                                </ul>
                              </li>
                              <li>
                                <code>c</code>
                              </li>
                            </ul>
                          </li>
                          <li>
                            <code>a</code>
                            <ul>
                              <li>
                                <code>a</code>
                              </li>
                              <li>
                                <code>b</code>
                              </li>
                              <li>
                                <code>c</code>
                              </li>
                            </ul>
                          </li>
                        </ul>
                      </li>
                    </ul>
                  </li>
                </ul>
              </li>
            </ul>
          </li>
        </ul>
      </SmartTree>
    </>
  );
}
