export default function Home() {
  return (
    <div>
      <figure>
        <figcaption>Example DOM structure diagram</figcaption>
        <ul className="tree">
          <li>
            <code>html</code>
            <ul>
              <li>
                <code>head</code>
                <ul>
                  <li>
                    <code>title</code>
                  </li>
                </ul>
              </li>
              <li>
                <code>body</code>
                <ul>
                  <li>
                    <code>header</code>
                    <ul>
                      <li>
                        <code>h1</code>
                      </li>
                      <li>
                        <code>p</code>
                      </li>
                    </ul>
                  </li>
                  <li>
                    <code>nav</code>
                    <ul>
                      <li>
                        <code>a</code>
                      </li>
                      <li>
                        <code>a</code>
                      </li>
                      <li>
                        <code>a</code>
                      </li>
                      <li>
                        <code>a</code>
                      </li>
                    </ul>
                  </li>
                  <li>
                    <code>main</code>
                    <ul>
                      <li>
                        <code>h1</code>
                      </li>
                      <li>
                        <code>article</code>
                        <ul>
                          <li>
                            <code>h2</code>
                          </li>
                          <li>
                            <code>p</code>
                          </li>
                          <li>
                            <code>p</code>
                          </li>
                        </ul>
                      </li>
                    </ul>
                  </li>
                  <li>
                    <code>aside</code>
                    <ul>
                      <li>
                        <code>h2</code>
                      </li>
                      <li>
                        <code>p</code>
                      </li>
                      <li>
                        <code>p</code>
                        <ul>
                          <li>
                            <code>a</code>
                          </li>
                        </ul>
                      </li>
                    </ul>
                  </li>
                  <li>
                    <code>footer</code>
                    <ul>
                      <li>
                        <code>nav</code>
                        <ul>
                          <li>
                            <code>a</code>
                          </li>
                          <li>
                            <code>a</code>
                            <div className="vertical-children">
                              <span
                                className="vertical-children__stem"
                                aria-hidden="true"
                              />
                              <span
                                className="vertical-children__top"
                                aria-hidden="true"
                              />
                              <ol className="vertical-children__list">
                                <li>
                                  <span
                                    className="vertical-children__branch"
                                    aria-hidden="true"
                                  />
                                  <code>a</code>
                                </li>
                                <li>
                                  <span
                                    className="vertical-children__branch"
                                    aria-hidden="true"
                                  />
                                  <code>bpiojwaegpoijaweg</code>
                                </li>
                                <li>
                                  <span
                                    className="vertical-children__branch"
                                    aria-hidden="true"
                                  />
                                  <code>c</code>
                                </li>
                              </ol>
                            </div>
                          </li>
                          <li>
                            <code>a</code>
                          </li>
                          <li>
                            <code>a</code>
                            <div className="vertical-children">
                              <span
                                className="vertical-children__stem"
                                aria-hidden="true"
                              />
                              <span
                                className="vertical-children__top"
                                aria-hidden="true"
                              />
                              <ol className="vertical-children__list">
                                <li>
                                  <span
                                    className="vertical-children__branch"
                                    aria-hidden="true"
                                  />
                                  <code>a</code>
                                </li>
                                <li>
                                  <span
                                    className="vertical-children__branch"
                                    aria-hidden="true"
                                  />
                                  <code>b</code>
                                </li>
                                <li>
                                  <span
                                    className="vertical-children__branch"
                                    aria-hidden="true"
                                  />
                                  <code>c</code>
                                </li>
                              </ol>
                            </div>
                          </li>
                        </ul>
                      </li>
                    </ul>
                  </li>
                </ul>
              </li>
            </ul>
          </li>
        </ul>
      </figure>
    </div>
  );
}
